PhoneStore/Web-dienthoai/Models/DetailsView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Web_dienthoai.Models
{
    public class DetailsView
    {
        public SanPham SanPham { get; set; }

        public List<HinhSP> HinhSP { get; set; }

        public ThongSo ThongSo { get; set; }

        public ThuongHieu ThuongHieu { get; set; }

    }
}

PhoneStore/Web-dienthoai/Models/KhachHang.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_dienthoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.DonHangs = new HashSet<DonHang>();
        }
    
        public int MaKH { get; set; }
        public string Hoten { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHangs { get; set; }
    }
}

PhoneStore/Web-dienthoai/Controllers/KhachHangsController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Web_dienthoai.Models;

namespace Web_dienthoai.Controllers
{
    public class KhachHangsController : Controller
    {
        private QLDienThoaiEntities db = new QLDienThoaiEntities();

        // GET: KhachHangs
        public ActionResult Index(string currentFilter, string s, int? page)
        {
            if (Session["Admin"] == null)
                return RedirectToAction("Login", "Admin");


            int pageSize = 7;
            int pageNum = (page ?? 1);

            if (s != null)
            {
                page = 1;
            }
            else
            {
                s = currentFilter;
            }

            var khachHang = from l in db.KhachHangs
                           select l;

            if (!String.IsNullOrEmpty(s))
            {
                khachHang = khachHang.Where(i => i.MaKH.ToString().Contains(s) ||
                i.Hoten.Contains(s) ||
                i.NgaySinh.ToString().Contains(s) ||
                i.Username.Contains(s) ||
                i.SDT.ToString().Contains(s));
            }

            ViewBag.CurrentFilter = s;

            khachHang = khachHang.OrderBy(id => id.Hoten);
            return View(khachHang.ToPagedList(pageNum, pageSize));
        }

        // GET: KhachHangs/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["Admin"] == null)
                return RedirectToAction("Login", "Admin");

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhachHang khachHang = db.KhachHangs.Find(id);
            if (khachHang == null)
            {
                return HttpNotFound();
            }
            return View(khachHang);
        }

        // GET: KhachHangs/Create
        public ActionResult Create()
        {
            if (Session["Admin"] == null)
                return RedirectToAction("Login", "Admin");

            List<SelectListItem> gioitinh = new List<SelectListItem>();
            gioitinh.Add(new SelectListItem { Text = "Nam", Value = "Nam" });
            gioitinh.Add(new SelectListItem { Text = "Nữ", Value = "Nữ" });
            ViewBag.Gioitinh = gioitinh;

            return View();
        }

        // POST: KhachHangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaKH,Hoten,SDT,DiaChi,GioiTinh,NgaySinh,Email,Username,Password")] KhachHang khachHang)
        {
            if (ModelState.IsValid)
            {
                db.KhachHangs.Add(khachHang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(khachHang);
        }

        // GET: KhachHangs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["Admin"] == null)
                return RedirectToAction("Login", "Admin");

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhachHang khachHang = db.KhachHangs.Find(id);
            if (khachHang == null)
            {
                return HttpNotFound();
            }
            return View(khachHang);
        }

        // POST: KhachHangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaKH,Hoten,SDT,DiaChi,GioiTinh,NgaySinh,Email,Username,Password")] KhachHang khachHang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(khachHang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(khachHang);
        }

        // GET: KhachHangs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["Admin"] == null)
                return RedirectToAction("Login", "Admin");

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhachHang khachHang = db.KhachHangs.Find(id);
            if (khachHang == null)
            {
                return HttpNotFound();
            }
            return View(khachHang);
        }

        // POST: KhachHangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            KhachHang khachHang = db.KhachHangs.Find(id);
            db.KhachHangs.Remove(khachHang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PhoneStore/Web-dienthoai/Views/KhachHangs/Create.cshtml
@model Web_dienthoai.Models.KhachHang

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<br />
<br />
@if (TempData["ThongBaoSuccess"] != null)
{
    <div class="alert alert-success d-flex" role="alert">
        <p>
            <i class="fas fa-check"></i> <span>@TempData["ThongBaoSuccess"].ToString()</span>
        </p>

    </div>
}
@if (TempData["ThongBaoFailed"] != null)
{
    <div class="alert alert-danger d-flex" role="alert">
        <p>
            <i class="fas fa-exclamation-circle"></i> <span>@TempData["ThongBaoFailed"].ToString()</span>
        </p>
    </div>
}

<div class="container" style="background-image: url('../../Images/gradient-background.jpg');">
    <div class="inner">

        @using (Html.BeginForm("Create", "KhachHangs", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <h3>Thêm Khách hàng</h3>

            <div class="form-group">
                <div class="form-wrapper">
                    Họ tên:
                    @Html.EditorFor(model => model.Hoten, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                    @Html.ValidationMessageFor(model => model.Hoten, "", new { @class = "text-danger" })
                </div>

                <div class="form-wrapper">
                    Giới tính:
                    @Html.DropDownList("Gioitinh", null, htmlAttributes: new { @class = "form-control", required = "required" })
                    @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-wrapper">
                Ngày sinh:
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control", type = "date", required = "required" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>

            <div class="form-wrapper">
                Số điện thoại:
                @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
            </div>

            <div class="form-wrapper">
                Địa chỉ:
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>

            <div class="form-wrapper">
                Email:
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>

            <input style="background-color:Green" type="submit" value="Xác nhận" class=" button1" />
        }
        <div style="margin-left:238px;color:#ccc">
            <a style="margin-left: -15px;" class="button1" href="~/KhachHangs/Index">Trở về</a>
        </div>
    </div>

</div>

PhoneStore/Web-dienthoai/Views/KhachHangs/Delete.cshtml
@model Web_dienthoai.Models.KhachHang

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>KhachHang</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Hoten)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hoten)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SDT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GioiTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgaySinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PhoneStore/Web-dienthoai/Views/KhachHangs/Details.cshtml
@model Web_dienthoai.Models.KhachHang

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<h2>Details</h2>

<div>
    <h4>KhachHang</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Hoten)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hoten)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SDT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GioiTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgaySinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaKH }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PhoneStore/Web-dienthoai/Views/KhachHangs/Edit.cshtml
@model Web_dienthoai.Models.KhachHang

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<br />
<br />
@if (TempData["ThongBaoSuccess"] != null)
{
    <div class="alert alert-success d-flex" role="alert">
        <p>
            <i class="fas fa-check"></i> <span>@TempData["ThongBaoSuccess"].ToString()</span>
        </p>

    </div>
}
@if (TempData["ThongBaoFailed"] != null)
{
    <div class="alert alert-danger d-flex" role="alert">
        <p>
            <i class="fas fa-exclamation-circle"></i> <span>@TempData["ThongBaoFailed"].ToString()</span>
        </p>
    </div>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>KhachHang</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaKH)

        <div class="form-group">
            @Html.LabelFor(model => model.Hoten, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hoten, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hoten, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SDT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Giới tính:
            @Html.DropDownListFor(model => model.GioiTinh,
            new List<SelectListItem>
            {
                new SelectListItem{Text="Nam", Value="Male"},
                new SelectListItem{Text="Nữ", Value="Female"}}, "Lựa chọn", new { @class = "form-control", required = "required" })
            @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PhoneStore/Web-dienthoai/Views/KhachHangs/Index.cshtml
@using Web_dienthoai.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<KhachHang>
@{
    ViewBag.Title = "QUẢN LÝ KHÁCH HÀNG";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<style>

    .delete-button {
        background-color: red;
        color: white;
        padding: 10px 20px;
        border-radius: 5px;
        border: none;
        text-decoration: none;
    }

    .edit-button {
        background-color: green;
        color: white;
        padding: 10px 20px;
        border-radius: 5px;
        border: none;
        text-decoration: none;
    }
</style>

<br />
<br />
@if (TempData["ThongBaoSuccess"] != null)
{
    <div class="alert alert-success d-flex" role="alert">
        <p>
            <i class="fas fa-check"></i> <span>@TempData["ThongBaoSuccess"].ToString()</span>
        </p>

    </div>
}
@if (TempData["ThongBaoFailed"] != null)
{
    <div class="alert alert-danger d-flex" role="alert">
        <p>
            <i class="fas fa-exclamation-circle"></i> <span>@TempData["ThongBaoFailed"].ToString()</span>
        </p>
    </div>
}

<div class="row mt-4">
    <div class="col-6">
        @Html.ActionLink("THÊM KHÁCH HÀNG", "Create", null, new { @class = "btn btn-success" })
    </div>
    <div class="col-6">
        <form style="width: 100%; padding-left: 250px;" action="/KhachHangs/Index" method="get">
            <div class="form-group">
                <input class="form-control" id="search" type="text" name="s" placeholder="Tìm kiếm khách hàng" value="" />
            </div>
        </form>
    </div>

    <table class="table">
        <tr>
            <th>
                Mã khách hàng
            </th>
            <th>
                Họ tên
            </th>
            <th>
                Tài khoản
            </th>
            <th>
                Số điện thoại
            </th>
            <th>
                Ngày sinh
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a style="text-decoration: none; color: black;" href="~/KhachHangs/Details?id=@item.MaKH">
                        @Html.DisplayFor(modelItem => item.MaKH)
                    </a>
                </td>
                <td>
                    <a style="text-decoration: none; color: black;" href="~/KhachHangs/Details?id=@item.MaKH">
                        @Html.DisplayFor(modelItem => item.Hoten)
                    </a>
                </td>
                <td>
                    <a style="text-decoration: none; color: black;" href="~/KhachHangs/Details?id=@item.MaKH">
                        @Html.DisplayFor(modelItem => item.Username)
                    </a>
                </td>
                <td>
                    <a style="text-decoration: none; color: black;" href="~/KhachHangs/Details?id=@item.MaKH">
                        @Html.DisplayFor(modelItem => item.SDT)
                    </a>
                </td>
                <td>
                    <a style="text-decoration: none; color: black;" href="~/KhachHangs/Details?id=@item.MaKH">
                        @Html.DisplayFor(modelItem => item.NgaySinh)
                    </a>
                </td>
                <td>
                    @*@Html.ActionLink("Edit", "Edit", new { id = item.MaKH }) |
                        @Html.ActionLink("Details", "Details", new { id = item.MaKH }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.MaKH })*@
                    <a class="edit-button fa fa-pencil" href="~/KhachHangs/Details?id=@item.MaKH"></a>
                    <a class="delete-button fa fa-trash" href="~/KhachHangs/Delete?id=@item.MaKH"></a>
                </td>
            </tr>
        }

    </table>
</div>



<!-- Thêm mã phân trang -->
<br />
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
    <div class="MenuTrang">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentFilter = ViewBag.CurrentFilter }))
    </div>
    <style>
        .MenuTrang li {
            display: inline;
            background-color: lightblue;
            color: white;
            padding: 10px 20px;
            margin: 2px 5px;
            border-radius: 5px;
            border: none;
            text-decoration: none;
        }
    </style>
    <!-- Kết thúc -->