PhoneStore/Web-dienthoai/Models/DetailsView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Web_dienthoai.Models
{
    public class DetailsView
    {
        public SanPham SanPham { get; set; }

        public List<HinhSP> HinhSP { get; set; }

        public ThongSo ThongSo { get; set; }

        public ThuongHieu ThuongHieu { get; set; }

    }
}

PhoneStore/Web-dienthoai/Controllers/ThongSoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Web_dienthoai.Models;

namespace Web_dienthoai.Controllers
{
    public class ThongSoesController : Controller
    {
        private QLDienThoaiEntities db = new QLDienThoaiEntities();

        // GET: ThongSoes
        public ActionResult Index(int id)
        {
            var thongSoes = db.ThongSoes.Where(s => s.IdSP== id);
            return PartialView(thongSoes.ToList());
        }

        // GET: ThongSoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ThongSo thongSo = db.ThongSoes.Find(id);
            if (thongSo == null)
            {
                return HttpNotFound();
            }
            return View(thongSo);
        }

        // GET: ThongSoes/Create
        public ActionResult Create(int id)
        {
            ThongSo thongSo = new ThongSo()
            {
                IdSP = id,
                TenTS = "Tên thông số..",
                Mota = ""
            };

            ViewBag.IdSP = new SelectList(db.SanPhams, "IdSP", "MaSP");
            return View(thongSo);
        }

        // POST: ThongSoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdSP,TenTS,Mota")] ThongSo thongSo)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.ThongSoes.Add(thongSo);
                    db.SaveChanges();
                    TempData["ThongBaoSuccess"] = "Thêm thành công " + thongSo.TenTS.ToString();
                    return RedirectToAction("Create", new {id = thongSo.IdSP});
                }
                catch (Exception ex)
                {
                    TempData["ThongBaoFailed"] = "Không thành công! Hãy thử lại.";
                    return RedirectToAction("Create", new { id = thongSo.IdSP });
                }
            }

            ViewBag.IdSP = new SelectList(db.SanPhams, "IdSP", "MaSP", thongSo.IdSP);
            return View(thongSo);
        }

        // GET: ThongSoes/Edit/5
        public ActionResult Edit(int id, string tents)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ThongSo thongSo = db.ThongSoes.First(ts => ts.IdSP == id && ts.TenTS == tents);
            if (thongSo == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdSP = new SelectList(db.SanPhams, "IdSP", "MaSP", thongSo.IdSP);
            return View(thongSo);
        }

        // POST: ThongSoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdSP,TenTS,Mota")] ThongSo thongSo)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Entry(thongSo).State = EntityState.Modified;
                    db.SaveChanges();
                    TempData["ThongBaoSuccess"] = "Cập nhật thông số " + thongSo.TenTS.ToString() + " thành công!";
                    return RedirectToAction("Edit", new {id = thongSo.TenTS});
                }
                catch(Exception ex)
                {
                    TempData["ThongBaoFailed"] = "Cập nhật thất bại!";
                    return RedirectToAction("Edit", new { id = thongSo.TenTS });
                }
            }
            ViewBag.IdSP = new SelectList(db.SanPhams, "IdSP", "MaSP", thongSo.IdSP);
            return View(thongSo);
        }

        // GET: ThongSoes/Delete/5
        public ActionResult Delete(int id, string tents)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ThongSo thongSo = db.ThongSoes.First(ts => ts.IdSP == id && ts.TenTS == tents);
            if (thongSo == null)
            {
                return HttpNotFound();
            }
            return View(thongSo);
        }

        // POST: ThongSoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, string tents)
        {
            ThongSo thongSo = db.ThongSoes.First(ts => ts.IdSP == id && ts.TenTS == tents);
            try
            {
                db.ThongSoes.Remove(thongSo);
                db.SaveChanges();
                TempData["ThongBaoSuccess"] = "Xóa thành công thông số " + thongSo.TenTS.ToString();
                return RedirectToAction("Details", "SanPhams", new { id = id });
            }
            catch(Exception ex)
            {
                TempData["ThongBaoFailed"] = "Xóa thất bại!";
                return RedirectToAction("Details", "SanPhams", new { id = id });
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PhoneStore/Web-dienthoai/Views/ThongSoes/Create.cshtml
@model Web_dienthoai.Models.ThongSo

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<br />
<br />
@if (TempData["ThongBaoSuccess"] != null)
{
    <div class="alert alert-success d-flex" role="alert">
        <p>
            <i class="fas fa-check"></i> <span>@TempData["ThongBaoSuccess"].ToString()</span>
        </p>

    </div>
}
@if (TempData["ThongBaoFailed"] != null)
{
    <div class="alert alert-danger d-flex" role="alert">
        <p>
            <i class="fas fa-exclamation-circle"></i> <span>@TempData["ThongBaoFailed"].ToString()</span>
        </p>
    </div>
}



<div class="container" style="background-image: url('../../Images/gradient-background.jpg');">
    <div class="inner">

        @using (Html.BeginForm("Create", "ThongSoes", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <h3>Thêm thông số</h3>

            <div class="form-wrapper" hidden>
                IdSP (*):
                @Html.EditorFor(model => model.IdSP, new { htmlAttributes = new { @class = "form-control", required = "required", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.IdSP, "", new { @class = "text-danger" })
            </div>

            <div class="form-wrapper">
                Tên thông số (*):
                @Html.EditorFor(model => model.TenTS, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.TenTS, "", new { @class = "text-danger" })
            </div>

            <div class="form-wrapper">
                Mô tả (*):
                @Html.EditorFor(model => model.Mota, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Mota, "", new { @class = "text-danger" })
            </div>


            <input style="background-color:Green" type="submit" value="Xác nhận" class=" button1" />
        }
    <div style="margin-left:238px;color:#ccc">
        <a style="margin-left: -15px;" class="button1" href="~/SanPhams/Details?id=@Model.IdSP">Trở về</a>
    </div>

    </div>

</div>

PhoneStore/Web-dienthoai/Views/ThongSoes/Delete.cshtml
@model Web_dienthoai.Models.ThongSo

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}



<<div class="wrapper">
    <div class="profile-card js-profile-card">
        <div class="profile-card__img">
            <img src="~/images/delete.jpg" alt="profile card">
        </div>

        <div class="profile-card__cnt js-profile-cnt">
            <h3>XÁC NHẬN XÓA THÔNG SỐ NÀY?</h3>
            <div class="profile-card__name">@Html.DisplayFor(model => model.TenTS)</div>
            <div class="profile-card__txt">Mã sản phẩm: <strong>@Html.DisplayFor(model => model.SanPham.MaSP)</strong> </div>

            <div class="profile-card__txt">Mô tả thông số:</div>
            <div class="profile-card-loc">
                <span class="profile-card-loc__icon">
                    <svg class="icon"><use xlink:href="#icon-location"></use></svg>
                </span>
                <span class="profile-card-loc__txt">
                    @Html.DisplayFor(model => model.Mota)
                </span>
            </div>
            <div class="profile-card-ctr">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <div class="profile-card-ctr">
                        <input type="submit" value="Delete" class="btn profile-card__button button--orange" />
                        <a class="profile-card__button button--blue" href="~/SanPhams/Details?id=@Model.IdSP">Trở về</a>
                    </div>
                }

            </div>

            <div class="profile-card-message js-message">
                <form class="profile-card-form">
                    <div class="profile-card-form__container">
                        <textarea placeholder="Say something..."></textarea>
                    </div>

                    <div class="profile-card-form__bottom">
                        <button class="profile-card__button button--blue js-message-close">
                        </button>

                        <button class="profile-card__button button--gray js-message-close">
                            Cancel
                        </button>
                    </div>
                </form>

                <div class="profile-card__overlay js-message-close"></div>
            </div>

        </div>

    </div>




    <script>
        var messageBox = document.querySelector('.js-message');
        var btn = document.querySelector('.js-message-btn');
        var card = document.querySelector('.js-profile-card');
        var closeBtn = document.querySelectorAll('.js-message-close');

        btn.addEventListener('click', function (e) {
            e.preventDefault();
            card.classList.add('active');
        });

        closeBtn.forEach(function (element, index) {
            console.log(element);
            element.addEventListener('click', function (e) {
                e.preventDefault();
                card.classList.remove('active');
            });
        });
    </script>

PhoneStore/Web-dienthoai/Views/ThongSoes/Details.cshtml
@model Web_dienthoai.Models.ThongSo

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<h2>Details</h2>

<div>
    <h4>ThongSo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Mota)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mota)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SanPham.MaSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SanPham.MaSP)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PhoneStore/Web-dienthoai/Views/ThongSoes/Edit.cshtml
@model Web_dienthoai.Models.ThongSo

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<br />
<br />
@if (TempData["ThongBaoSuccess"] != null)
{
    <div class="alert alert-success d-flex" role="alert">
        <p>
            <i class="fas fa-check"></i> <span>@TempData["ThongBaoSuccess"].ToString()</span>
        </p>

    </div>
}
@if (TempData["ThongBaoFailed"] != null)
{
    <div class="alert alert-danger d-flex" role="alert">
        <p>
            <i class="fas fa-exclamation-circle"></i> <span>@TempData["ThongBaoFailed"].ToString()</span>
        </p>
    </div>
}

<div class="container" style="background-image: url('../../Images/gradient-background.jpg');">
    <div class="inner">
        @using (Html.BeginForm("Edit", "ThongSoes", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            <h3>Cập nhập thông số sản phẩm</h3>

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.IdSP)

                <div class="form-wrapper">
                    <p class="col-md-10">Tên thông số</p>
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.TenTS, new { @readonly = "readonly", @class = "form-control", required = "required" })
                        @Html.ValidationMessageFor(model => model.TenTS, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-wrapper">
                    <p class="col-md-10">Mô tả</p>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Mota, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Mota, "", new { @class = "text-danger" })
                    </div>
                </div>



            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input style="margin-left:-15px;background-color:Green" type="submit" value="Lưu" class=" button1" />
                    <a style="margin-left: -15px;" class="button1" href="~/SanPhams/Details?id=@Model.IdSP">Trở về</a>
                </div>
            </div>
        }

    </div>

</div>

PhoneStore/Web-dienthoai/Views/ThongSoes/Index.cshtml
@model IEnumerable<Web_dienthoai.Models.ThongSo>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            Thông số kỹ thuật
        </button>
    </h2>
    @foreach (var item in Model)
    {
        <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                <div class="form-group">
                    <strong>@item.TenTS</strong>
                    <div class="col-md-10">
                        @item.Mota
                    </div>
                </div>
            </div>
        </div>
    }
</div>