PhoneStore/Web-dienthoai/Models/DetailsView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Web_dienthoai.Models
{
    public class DetailsView
    {
        public SanPham SanPham { get; set; }

        public List<HinhSP> HinhSP { get; set; }

        public ThongSo ThongSo { get; set; }

        public ThuongHieu ThuongHieu { get; set; }

    }
}

PhoneStore/Web-dienthoai/Models/TaiKhoanNV.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_dienthoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoanNV
    {
        public int MaNV { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}

PhoneStore/Web-dienthoai/Controllers/TaiKhoanNVsController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Web_dienthoai.Models;

namespace Web_dienthoai.Controllers
{
    public class TaiKhoanNVsController : Controller
    {
        private QLDienThoaiEntities db = new QLDienThoaiEntities();

        // GET: TaiKhoanNVs
        public ActionResult Index(string currentFilter, string s, int? page)
        {
            if (Session["Admin"] == null)
                return RedirectToAction("Login", "Admin");


            int pageSize = 7;
            int pageNum = (page ?? 1);

            if (s != null)
            {
                page = 1;
            }
            else
            {
                s = currentFilter;
            }

            var taiKhoanNV = from l in db.TaiKhoanNVs.Include(t => t.NhanVien)
                           select l;

            if (!String.IsNullOrEmpty(s))
            {
                taiKhoanNV = taiKhoanNV.Where(i => i.Username.Contains(s) || i.NhanVien.Hoten.Contains(s));
            }
            ViewBag.CurrentFilter = s;

            taiKhoanNV = taiKhoanNV.OrderBy(id => id.Username);

            return View(taiKhoanNV.ToPagedList(pageNum, pageSize));
        }

        // GET: TaiKhoanNVs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoanNV taiKhoanNV = db.TaiKhoanNVs.Find(id);
            if (taiKhoanNV == null)
            {
                return HttpNotFound();
            }
            return View(taiKhoanNV);
        }

        // GET: TaiKhoanNVs/Create
        public ActionResult Create()
        {
            ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "Hoten");
            return View();
        }

        // POST: TaiKhoanNVs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaNV,Username,Password")] TaiKhoanNV taiKhoanNV)
        {
            if (ModelState.IsValid)
            {
                var validTK = db.TaiKhoanNVs.Include(taiKhoanNV.Username);
                if (validTK == null)
                {
                    ViewBag["ThongBaoFailed"] = "Đã tồn tại tên tài khoản! Vui lòng chọn tên khác";
                    return View("Create");
                }
                else
                {
                    db.TaiKhoanNVs.Add(taiKhoanNV);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "Hoten", taiKhoanNV.MaNV);
            return View(taiKhoanNV);
        }

        // GET: TaiKhoanNVs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoanNV taiKhoanNV = db.TaiKhoanNVs.Find(id);
            if (taiKhoanNV == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "Hoten", taiKhoanNV.MaNV);
            return View(taiKhoanNV);
        }

        // POST: TaiKhoanNVs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaNV,Username,Password")] TaiKhoanNV taiKhoanNV)
        {
            if (ModelState.IsValid)
            {
                db.Entry(taiKhoanNV).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "Hoten", taiKhoanNV.MaNV);
            return View(taiKhoanNV);
        }

        // GET: TaiKhoanNVs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoanNV taiKhoanNV = db.TaiKhoanNVs.Find(id);
            if (taiKhoanNV == null)
            {
                return HttpNotFound();
            }
            return View(taiKhoanNV);
        }

        // POST: TaiKhoanNVs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TaiKhoanNV taiKhoanNV = db.TaiKhoanNVs.Find(id);
            db.TaiKhoanNVs.Remove(taiKhoanNV);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PhoneStore/Web-dienthoai/Views/TaiKhoanNVs/Create.cshtml
@model Web_dienthoai.Models.TaiKhoanNV

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<link href="~/Content/bootstrap-chosen.css" rel="stylesheet" />

@if (TempData["ThongBaoSuccess"] != null)
{
    <div class="alert alert-success d-flex" role="alert">
        <p>
            <i class="fas fa-check"></i> <span>@TempData["ThongBaoSuccess"].ToString()</span>
        </p>

    </div>
}
@if (TempData["ThongBaoFailed"] != null)
{
    <div class="alert alert-danger d-flex" role="alert">
        <p>
            <i class="fas fa-exclamation-circle"></i> <span>@TempData["ThongBaoFailed"].ToString()</span>
        </p>
    </div>
}


<div class="container" style="background-image: url('../../Images/gradient-background.jpg'); border-radius:8px;">
    <div class="inner">

        @using (Html.BeginForm("Create", "TaiKhoanNVs", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <h3>Thêm thương hiệu</h3>
            <div class="form-wrapper">
                Họ tên nhân viên:
                @Html.DropDownList("MaNV", null, htmlAttributes: new { @class = "form-control", @id = "nvDropdown", required = "required" })
                @Html.ValidationMessageFor(model => model.MaNV, "", new { @class = "text-danger" })
            </div>


            <div class="form-wrapper">
                Tên tài khoản:
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>

            <div class="form-wrapper">
                Mật khẩu:
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", required = "required", type = "password" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>

            <input style="background-color:Green" type="submit" value="Xác nhận" class=" button1" />
        }
        <div style="margin-left:238px;color:#ccc">
            <a style="margin-left: -15px;" class="button1" href="~/TaiKhoanNVs/Index">Trở về</a>
        </div>
    </div>

</div>

<script type="text/javascript">
    $(function () {
        $("#nvDropdown").chosen();
    });
</script>

PhoneStore/Web-dienthoai/Views/TaiKhoanNVs/Delete.cshtml
@model Web_dienthoai.Models.TaiKhoanNV

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<<div class="wrapper">
    <div class="profile-card js-profile-card">
        <div class="profile-card__img">
            <img src="~/images/delete.jpg" alt="profile card">
        </div>

        <div class="profile-card__cnt js-profile-cnt">
            <h3>XÁC NHẬN XÓA THƯƠNG HIỆU NÀY?</h3>
            <div class="profile-card__name">@Html.DisplayFor(model => model.NhanVien.Hoten)</div>
            <div class="profile-card__txt">Mã Thương Hiệu: <strong>@Html.DisplayFor(model => model.Username)</strong> </div>


            <div class="profile-card-ctr">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <div class="profile-card-ctr">
                        <input type="submit" value="Delete" class="btn profile-card__button button--orange" />
                        <a class="profile-card__button button--blue" href="~/TaiKhoanNVs/Index">Trở về</a>
                    </div>
                }

            </div>

            <div class="profile-card-message js-message">
                <form class="profile-card-form">
                    <div class="profile-card-form__container">
                        <textarea placeholder="Say something..."></textarea>
                    </div>

                    <div class="profile-card-form__bottom">
                        <button class="profile-card__button button--blue js-message-close">
                        </button>

                        <button class="profile-card__button button--gray js-message-close">
                            Cancel
                        </button>
                    </div>
                </form>

                <div class="profile-card__overlay js-message-close"></div>
            </div>

        </div>

    </div>

PhoneStore/Web-dienthoai/Views/TaiKhoanNVs/Details.cshtml
@model Web_dienthoai.Models.TaiKhoanNV

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<div class="wrapper">
    <div class="profile-card js-profile-card">
        <div class="profile-card__img">
            <img src="~/images/brand_logo.png" alt="profile card">
        </div>

        <div class="profile-card__cnt js-profile-cnt">
            <div class="profile-card__name">@Html.DisplayFor(model => model.NhanVien.Hoten)</div>
            <div class="profile-card__txt">Tên tài khoản: <strong>@Html.DisplayFor(model => model.Username)</strong> </div>


            <div class="profile-card-ctr">
                @if (Session["Admin"] != null)
                {
                    <a class="profile-card__button button--orange" href="~/TaiKhoanNVs/Edit?id=@Model.MaNV">Chỉnh sửa</a>
                }
                <a class="profile-card__button button--blue" href="~/TaiKhoanNVs/Index">Trở về</a>
            </div>

        </div>

        <div class="profile-card-message js-message">
            <form class="profile-card-form">
                <div class="profile-card-form__container">
                    <textarea placeholder="Say something..."></textarea>
                </div>

                <div class="profile-card-form__bottom">
                    <button class="profile-card__button button--blue js-message-close">
                    </button>

                    <button class="profile-card__button button--gray js-message-close">
                        Cancel
                    </button>
                </div>
            </form>

            <div class="profile-card__overlay js-message-close"></div>
        </div>

    </div>

</div>




<script>
    var messageBox = document.querySelector('.js-message');
    var btn = document.querySelector('.js-message-btn');
    var card = document.querySelector('.js-profile-card');
    var closeBtn = document.querySelectorAll('.js-message-close');

    btn.addEventListener('click', function (e) {
        e.preventDefault();
        card.classList.add('active');
    });

    closeBtn.forEach(function (element, index) {
        console.log(element);
        element.addEventListener('click', function (e) {
            e.preventDefault();
            card.classList.remove('active');
        });
    });
</script>

PhoneStore/Web-dienthoai/Views/TaiKhoanNVs/Edit.cshtml
@model Web_dienthoai.Models.TaiKhoanNV

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<br />
<br />
@if (TempData["ThongBaoSuccess"] != null)
{
    <div class="alert alert-success d-flex" role="alert">
        <p>
            <i class="fas fa-check"></i> <span>@TempData["ThongBaoSuccess"].ToString()</span>
        </p>

    </div>
}
@if (TempData["ThongBaoFailed"] != null)
{
    <div class="alert alert-danger d-flex" role="alert">
        <p>
            <i class="fas fa-exclamation-circle"></i> <span>@TempData["ThongBaoFailed"].ToString()</span>
        </p>
    </div>
}

<div class="container" style="background-image: url('../../Images/gradient-background.jpg'); border-radius:8px;">
    <div class="inner">
        @using (Html.BeginForm("Edit", "TaiKhoanNVs", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            <h3>Cập nhập thông tin Thương hiệu</h3>
            <div class="form-group">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.MaNV)

                <div class="form-wrapper">
                    <p class="col-md-10">Tên tài khoản</p>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                        @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-wrapper">
                    <p class="col-md-10">Mật khẩu</p>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", required = "required", type = "password" } })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                </div>


            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input style="margin-left:-15px;background-color:Green" type="submit" value="Lưu" class=" button1" />
                    <a style="margin-left: -15px;" class="button1" href="~/TaiKhoanNVs/Details?id=@Model.MaNV">Trở về</a>
                </div>
            </div>
        }

    </div>

</div>

PhoneStore/Web-dienthoai/Views/TaiKhoanNVs/Index.cshtml
@using Web_dienthoai.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<TaiKhoanNV>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<style>

    .delete-button {
        background-color: red;
        color: white;
        padding: 10px 20px;
        border-radius: 5px;
        border: none;
        text-decoration: none;
    }

    .edit-button {
        background-color: green;
        color: white;
        padding: 10px 20px;
        border-radius: 5px;
        border: none;
        text-decoration: none;
    }
</style>

<br />
<br />
@if (TempData["ThongBaoSuccess"] != null)
{
    <div class="alert alert-success d-flex" role="alert">
        <p>
            <i class="fas fa-check"></i> <span>@TempData["ThongBaoSuccess"].ToString()</span>
        </p>

    </div>
}
@if (TempData["ThongBaoFailed"] != null)
{
    <div class="alert alert-danger d-flex" role="alert">
        <p>
            <i class="fas fa-exclamation-circle"></i> <span>@TempData["ThongBaoFailed"].ToString()</span>
        </p>
    </div>
}

<div class="row mt-4">
    <div class="col-6">
        @Html.ActionLink("THÊM TÀI KHOẢN", "Create", null, new { @class = "btn btn-success" })
    </div>

    <div class="col-6">
        <form style="width: 100%; padding-left: 250px;" action="/TaiKhoanNVs/Index" method="get">
            <div class="form-group">
                <input class="form-control" id="search" type="text" name="s" placeholder="Tìm kiếm tài khoản" value="" />
            </div>
        </form>
    </div>

    <table class="table">
        <tr>
            <th>
                Username
            </th>
            <th>
                Họ và tên
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a style="text-decoration: none; color: black;" href="~/TaiKhoanNVs/Details?id=@item.MaNV">
                        @Html.DisplayFor(modelItem => item.Username)
                    </a>
                </td>
                <td>
                    <a style="text-decoration: none; color: black;" href="~/TaiKhoanNVs/Details?id=@item.MaNV">
                        @Html.DisplayFor(modelItem => item.NhanVien.Hoten)
                    </a>
                </td>

                <td>
                    <a class="edit-button fa fa-pencil" href="~/TaiKhoanNVs/Details?id=@item.MaNV"></a>
                    <a class="delete-button fa fa-trash" href="~/TaiKhoanNVs/Delete?id=@item.MaNV"></a>
                </td>
            </tr>
        }

    </table>
</div>

<!-- Thêm mã phân trang -->
<br />
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
    <div class="MenuTrang">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentFilter = ViewBag.CurrentFilter }))
    </div>
    <style>
        .MenuTrang li {
            display: inline;
            background-color: lightblue;
            color: white;
            padding: 10px 20px;
            margin: 2px 5px;
            border-radius: 5px;
            border: none;
            text-decoration: none;
        }
    </style>
    <!-- Kết thúc -->