PhoneStore/Web-dienthoai/Models/DetailsView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Web_dienthoai.Models
{
    public class DetailsView
    {
        public SanPham SanPham { get; set; }

        public List<HinhSP> HinhSP { get; set; }

        public ThongSo ThongSo { get; set; }

        public ThuongHieu ThuongHieu { get; set; }

    }
}

PhoneStore/Web-dienthoai/Models/DonHang.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_dienthoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.ChiTietDHs = new HashSet<ChiTietDH>();
        }
    
        public long MaDH { get; set; }
        public Nullable<int> MaKH { get; set; }
        public string TenNguoiNhan { get; set; }
        public string SDTnhan { get; set; }
        public string DiaChiNhan { get; set; }
        public Nullable<decimal> TriGia { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<System.DateTime> NgayDH { get; set; }
        public string HTThanhToan { get; set; }
        public string HTGiaohang { get; set; }
        public Nullable<int> MaNV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDH> ChiTietDHs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}

PhoneStore/Web-dienthoai/Controllers/DonHangsController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Web_dienthoai.Models;

namespace Web_dienthoai.Controllers
{
    public class DonHangsController : Controller
    {
        private QLDienThoaiEntities db = new QLDienThoaiEntities();

        // GET: DonHangs
        public ActionResult Index(string currentFilter, string s, int? page)
        {
            if (Session["Admin"] == null)
                return RedirectToAction("Login", "Admin");


            int pageSize = 7;
            int pageNum = (page ?? 1);

            if (s != null)
            {
                page = 1;
            }
            else
            {
                s = currentFilter;
            }

            var donHangs = from l in db.DonHangs
                           select l;
            donHangs = donHangs.Where(i => i.TinhTrang.Contains("Chờ duyệt") || i.TinhTrang.Contains("Đang xử lý"));
            if (!String.IsNullOrEmpty(s))
            {
                donHangs = donHangs.Where(id => id.MaDH.ToString().Contains(s) || id.TenNguoiNhan.Contains(s) || id.NgayDH.ToString().Contains(s) || id.SDTnhan.ToString().Contains(s));
            }

            donHangs = donHangs.OrderBy(i => i.NgayDH);
            return View(donHangs.ToPagedList(pageNum, pageSize));
        }

        public ActionResult DonHangDaGiao(string currentFilter, string s, int? page)
        {
            if (Session["Admin"] == null)
                return RedirectToAction("Login", "Admin");


            int pageSize = 7;
            int pageNum = (page ?? 1);

            if (s != null)
            {
                page = 1;
            }
            else
            {
                s = currentFilter;
            }

            var donHangs = from l in db.DonHangs
                           select l;
            donHangs = donHangs.Where(i => i.TinhTrang.Contains("Đã giao"));
            if (!String.IsNullOrEmpty(s))
            {
                donHangs = donHangs.Where(id => id.MaDH.ToString().Contains(s) || id.TenNguoiNhan.Contains(s) || id.NgayDH.ToString().Contains(s) || id.SDTnhan.ToString().Contains(s));
            }

            donHangs = donHangs.OrderBy(i => i.NgayDH);
            return View(donHangs.ToPagedList(pageNum, pageSize));
        }

        public ActionResult DonHangDaHuy(string currentFilter, string s, int? page)
        {
            if (Session["Admin"] == null)
                return RedirectToAction("Login", "Admin");


            int pageSize = 7;
            int pageNum = (page ?? 1);

            if (s != null)
            {
                page = 1;
            }
            else
            {
                s = currentFilter;
            }

            var donHangs = from l in db.DonHangs
                           select l;
            donHangs = donHangs.Where(i => i.TinhTrang.Contains("Hủy"));
            if (!String.IsNullOrEmpty(s))
            {
                donHangs = donHangs.Where(id => id.MaDH.ToString().Contains(s) || id.TenNguoiNhan.Contains(s) || id.NgayDH.ToString().Contains(s) || id.SDTnhan.ToString().Contains(s));
            }

            donHangs = donHangs.OrderBy(i => i.NgayDH);
            return View(donHangs.ToPagedList(pageNum, pageSize));
        }

        // GET: DonHangs/Details/5
        public ActionResult Details(long? id)
        {
            if (Session["Admin"] == null)
                return RedirectToAction("Login", "Admin");

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonHang donHang = db.DonHangs.Find(id);
            if (donHang == null)
            {
                return HttpNotFound();
            }
            return View(donHang);
        }

        // GET: DonHangs/Create
        public ActionResult Create()
        {
            if (Session["Admin"] == null)
                return RedirectToAction("Login", "Admin");

            ViewBag.MaKH = new SelectList(db.KhachHangs, "MaKH", "Hoten");
            ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "Hoten");
            return View();
        }

        // POST: DonHangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaKH,TenNguoiNhan,SDTnhan,DiaChiNhan,HTThanhToan,HTGiaohang")] DonHang donHang)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    TaiKhoanNV nv = Session["Admin"] as TaiKhoanNV;
                    donHang.MaNV = nv.MaNV;
                    donHang.TriGia = (decimal)1;
                    donHang.NgayDH = DateTime.Now;
                    donHang.TinhTrang = "Đang xử lý";
                    db.DonHangs.Add(donHang);
                    db.SaveChanges();
                    TempData["ThongBaoSuccess"] = "Đơn hàng " + donHang.MaDH + " đã được tạo!";
                    return RedirectToAction("Create");
                }
                catch(Exception ex)
                {
                    TempData["ThongBaoFailed"] = "Thất bại khi tạo đơn hàng!";
                    return RedirectToAction("Create");
                }
                
            }

            ViewBag.MaKH = new SelectList(db.KhachHangs, "MaKH", "Hoten", donHang.MaKH);
            ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "Hoten", donHang.MaNV);
            return View(donHang);
        }

        // GET: DonHangs/Edit/5
        public ActionResult Edit(int id)
        {
            if (Session["Admin"] == null)
                return RedirectToAction("Login", "Admin");

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonHang donHang = db.DonHangs.Find(id);
            if (donHang == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaKH = new SelectList(db.KhachHangs, "MaKH", "Hoten", donHang.MaKH);
            ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "Hoten", donHang.MaNV);
            return View(donHang);
        }

        // POST: DonHangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaDH,MaKH,TenNguoiNhan,SDTnhan,DiaChiNhan,TriGia,TinhTrang,NgayDH,HTThanhToan,HTGiaohang,MaNV")] DonHang donHang)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Entry(donHang).State = EntityState.Modified;
                    db.SaveChanges();
                    TempData["ThongBaoSuccess"] = "Đã cập nhật đơn hàng " + donHang.MaDH;
                    return RedirectToAction("Edit", new {id = donHang.MaDH});
                }
                catch(Exception ex)
                {
                    TempData["ThongBaoFailed"] = "Cập nhật đơn hàng thất bại!";
                    return RedirectToAction("Edit", new { id = donHang.MaDH });
                }
            }
            ViewBag.MaKH = new SelectList(db.KhachHangs, "MaKH", "Hoten", donHang.MaKH);
            ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "Hoten", donHang.MaNV);
            return View(donHang);
        }

        // GET: DonHangs/Delete/5
        public ActionResult Delete(long? id)
        {
            if (Session["Admin"] == null)
                return RedirectToAction("Login", "Admin");

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonHang donHang = db.DonHangs.Find(id);
            if (donHang == null)
            {
                return HttpNotFound();
            }
            return View(donHang);
        }

        // POST: DonHangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            DonHang donHang = db.DonHangs.Find(id);
            var ctdonhang = db.ChiTietDHs.Where(c => c.MaDH == donHang.MaDH).ToList();
            foreach (var c in ctdonhang)
            {
                db.ChiTietDHs.Remove(c);
            }
            db.DonHangs.Remove(donHang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

PhoneStore/Web-dienthoai/Views/DonHangs/Create.cshtml
@model Web_dienthoai.Models.DonHang

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<br />
<br />
@if (TempData["ThongBaoSuccess"] != null)
{
    <div class="alert alert-success d-flex" role="alert">
        <p>
            <i class="fas fa-check"></i> <span>@TempData["ThongBaoSuccess"].ToString()</span>
        </p>

    </div>
}
@if (TempData["ThongBaoFailed"] != null)
{
    <div class="alert alert-danger d-flex" role="alert">
        <p>
            <i class="fas fa-exclamation-circle"></i> <span>@TempData["ThongBaoFailed"].ToString()</span>
        </p>
    </div>
}

<div class="container" style="background-image: url('../../Images/gradient-background.jpg'); border-radius: 8px">
    <div class="inner">

        @using (Html.BeginForm("Create", "DonHangs", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <h3>Thêm Đơn hàng</h3>

            <div class="form-wrapper">
                Khách hàng (*):
                @Html.DropDownList("MaKH", null, htmlAttributes: new { @class = "form-control", required = "required" })
                @Html.ValidationMessageFor(model => model.MaKH, "", new { @class = "text-danger" })
            </div>

            <div class="form-wrapper">
                Tên người nhận (*):
                @Html.EditorFor(model => model.TenNguoiNhan, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.TenNguoiNhan, "", new { @class = "text-danger" })
            </div>

            <div class="form-wrapper">
                Số điện thoại (*):
                @Html.EditorFor(model => model.SDTnhan, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.SDTnhan, "", new { @class = "text-danger" })
            </div>

            <div class="form-wrapper">
                Địa chỉ (*):
                @Html.EditorFor(model => model.DiaChiNhan, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.DiaChiNhan, "", new { @class = "text-danger" })
            </div>

            <div class="form-wrapper">
                Hình thức thanh toán (*)
                @Html.EditorFor(model => model.HTThanhToan, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.HTThanhToan, "", new { @class = "text-danger" })
            </div>

            <div class="form-wrapper">
                Hình thức giao hàng (*)
                @Html.EditorFor(model => model.HTGiaohang, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.HTGiaohang, "", new { @class = "text-danger" })
            </div>

            <input style="background-color:Green" type="submit" value="Xác nhận" class=" button1" />
        }
    <div style="margin-left:238px;color:#ccc">
        <a style="margin-left: -15px;" class="button1" href="~/DonHangs/Index">Trở về</a>
    </div>
    </div>

</div>

PhoneStore/Web-dienthoai/Views/DonHangs/Delete.cshtml
@model Web_dienthoai.Models.DonHang

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DonHang</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenNguoiNhan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNguoiNhan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SDTnhan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDTnhan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiaChiNhan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChiNhan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TriGia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TriGia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TinhTrang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TinhTrang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayDH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayDH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HTThanhToan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HTThanhToan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HTGiaohang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HTGiaohang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KhachHang.Hoten)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KhachHang.Hoten)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhanVien.Hoten)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhanVien.Hoten)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PhoneStore/Web-dienthoai/Views/DonHangs/Details.cshtml
@model Web_dienthoai.Models.DonHang

@{
    ViewBag.Title = "CHI TIẾT ĐƠN HÀNG";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}



<div class="wrapper">
    <div class="profile-card js-profile-card">
        <div class="profile-card__img">
            <img src="~/images/avatar.png" alt="profile card">
        </div>

        <div class="profile-card__cnt js-profile-cnt">
            <div class="profile-card__name">@Html.DisplayFor(model => model.TenNguoiNhan)</div>
            <div class="profile-card__txt">Mã Khách hàng: <strong>@Html.DisplayFor(model => model.MaKH)</strong> </div>
            <div class="profile-card__txt">Số điện thoại: <strong>@Html.DisplayFor(model => model.SDTnhan)</strong> </div>
            <div class="profile-card__txt">Tổng trị giá: <strong>@Html.DisplayFor(model => model.TriGia)</strong> </div>
            <div class="profile-card__txt">Tình trạng: <strong>@Html.DisplayFor(model => model.TinhTrang)</strong> </div>
            <div class="profile-card__txt">Ngày đặt hàng: <strong>@Html.DisplayFor(model => model.NgayDH)</strong> </div>
            <div class="profile-card__txt">Hình thức thanh toán: <strong>@Html.DisplayFor(model => model.HTThanhToan)</strong> </div>
            <div class="profile-card__txt">Hình thức giao hàng: <strong>@Html.DisplayFor(model => model.HTGiaohang)</strong> </div>
            <div class="profile-card__txt">Nhân viên xử lý: <strong>@Html.DisplayFor(model => model.NhanVien.Hoten)</strong> </div>


            <div class="profile-card-loc">
                <span class="profile-card-loc__icon">
                    <svg class="icon"><use xlink:href="#icon-location"></use></svg>
                </span>
                <span class="profile-card-loc__txt">
                    @Html.DisplayFor(model => model.DiaChiNhan)
                </span>
            </div>



            <div class="profile-card-ctr">
                @if (Session["Admin"] != null)
                {
                    <a class="profile-card__button button--orange" href="~/DonHangs/Edit?id=@Model.MaDH">Chỉnh sửa</a>
                }
                <a class="profile-card__button button--blue" href="~/DonHangs/Index">Trở về</a>
            </div>

        </div>

        <div class="profile-card-message js-message">
            <form class="profile-card-form">
                <div class="profile-card-form__container">
                    <textarea placeholder="Say something..."></textarea>
                </div>

                <div class="profile-card-form__bottom">
                    <button class="profile-card__button button--blue js-message-close">
                    </button>

                    <button class="profile-card__button button--gray js-message-close">
                        Cancel
                    </button>
                </div>
            </form>

            <div class="profile-card__overlay js-message-close"></div>
        </div>

    </div>

</div>

PhoneStore/Web-dienthoai/Views/DonHangs/DonHangDaGiao.cshtml
@using Web_dienthoai.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<DonHang>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}
<style>

    .delete-button {
        background-color: red;
        color: white;
        padding: 10px 20px;
        border-radius: 5px;
        border: none;
        text-decoration: none;
    }

    .edit-button {
        background-color: green;
        color: white;
        padding: 10px 20px;
        border-radius: 5px;
        border: none;
        text-decoration: none;
    }
</style>

<div class="row mt-4">
    <div class="col-6">
        @*@Html.ActionLink("THÊM ĐƠN HÀNG", "Create", null, new { @class = "btn btn-success" })*@
    </div>
    <div class="col-6">
        <form style="width: 100%; padding-left: 250px;" action="/DonHangs/DonHangDaGiao" method="get">
            <div class="form-group">
                <input class="form-control" id="search" type="text" name="s" placeholder="Tìm kiếm đơn hàng" value="" />
            </div>
        </form>
    </div>

    <table class="table">
        <tr>
            <th>
                Mã đơn hàng
            </th>
            <th>
                Tên người nhận
            </th>
            <th>
                Số điện thoại
            </th>
            <th>
                Ngày đặt hàng
            </th>
            <th>
                Tình trạng
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a style="text-decoration: none; color: black;" href="~/DonHangs/Details?id=@item.MaDH">
                        @Html.DisplayFor(modelItem => item.MaDH)
                    </a>
                </td>
                <td>
                    <a style="text-decoration: none; color: black;" href="~/DonHangs/Details?id=@item.MaDH">
                        @Html.DisplayFor(modelItem => item.TenNguoiNhan)
                    </a>
                </td>
                <td>
                    <a style="text-decoration: none; color: black;" href="~/DonHangs/Details?id=@item.MaDH">
                        @Html.DisplayFor(modelItem => item.SDTnhan)
                    </a>
                </td>
                <td>
                    <a style="text-decoration: none; color: black;" href="~/DonHangs/Details?id=@item.MaDH">
                        @Html.DisplayFor(modelItem => item.NgayDH)
                    </a>
                </td>
                <td>
                    <a style="text-decoration: none; color: black;" href="~/DonHangs/Details?id=@item.MaDH">
                        @Html.DisplayFor(modelItem => item.TinhTrang)
                    </a>
                </td>
                <td>
                    @*@Html.ActionLink("Edit", "Edit", new { id = item.MaDH }) |
                        @Html.ActionLink("Details", "Details", new { id = item.MaDH }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.MaDH })*@
                    <a class="edit-button fa fa-pencil" href="~/DonHangs/Details?id=@item.MaDH"></a>
                    <a class="delete-button fa fa-trash" href="~/DonHangs/Delete?id=@item.MaDH"></a>
                </td>
            </tr>
        }

    </table>
</div>


<!-- Thêm mã phân trang -->
<br />
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
    <div class="MenuTrang">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentFilter = ViewBag.CurrentFilter }))
    </div>
    <style>
        .MenuTrang li {
            display: inline;
            background-color: lightblue;
            color: white;
            padding: 10px 20px;
            margin: 2px 5px;
            border-radius: 5px;
            border: none;
            text-decoration: none;
        }
    </style>
    <!-- Kết thúc -->

PhoneStore/Web-dienthoai/Views/DonHangs/Edit.cshtml
@model Web_dienthoai.Models.DonHang

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<br />
<br />
@if (TempData["ThongBaoSuccess"] != null)
{
    <div class="alert alert-success d-flex" role="alert">
        <p>
            <i class="fas fa-check"></i> <span>@TempData["ThongBaoSuccess"].ToString()</span>
        </p>

    </div>
}
@if (TempData["ThongBaoFailed"] != null)
{
    <div class="alert alert-danger d-flex" role="alert">
        <p>
            <i class="fas fa-exclamation-circle"></i> <span>@TempData["ThongBaoFailed"].ToString()</span>
        </p>
    </div>
}

<div class="container" style="background-image: url('../../Images/gradient-background.jpg');">
    <div class="inner">
        @using (Html.BeginForm("Edit", "DonHangs", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            <h3>Cập nhập thông tin Đơn hàng</h3>
            <div class="form-group">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.MaKH)
                @Html.HiddenFor(model => model.MaDH)

                <div class="form-wrapper">
                    <p class="col-md-10">Tên người nhận</p>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TenNguoiNhan, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.TenNguoiNhan, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-wrapper">
                    <p class="col-md-10">Số điện thoại nhận</p>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.SDTnhan, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.SDTnhan, "", new { @class = "text-danger" })
                    </div>
                </div>

            </div>

            <div class="form-wrapper">
                <p class="col-md-10">Địa chỉ nhận</p>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DiaChiNhan, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.DiaChiNhan, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-wrapper">
                <p class="col-md-10">Tổng trị giá đơn hàng</p>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TriGia, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.TriGia, "", new { @class = "text-danger" })
                </div>
            </div>



            <div class="form-wrapper">
                <p class="col-md-10">Ngày đặt hàng</p>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NgayDH, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.NgayDH, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-wrapper">
                <p class="col-md-10">Hình thức giao hàng</p>
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.HTGiaohang,
            new List<SelectListItem>
            {
                new SelectListItem{Text="Giao hàng tiêu chuẩn", Value="Giao hàng tiêu chuẩn"},
                new SelectListItem{Text="Giao hàng hỏa tốc", Value="Giao hàng hỏa tốc" }}, "Lựa chọn", new { @class = "form-control", required = "required" })
                    @Html.ValidationMessageFor(model => model.HTGiaohang, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-wrapper">
                <p class="col-md-10">Tình trạng đơn hàng</p>
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.TinhTrang,
            new List<SelectListItem>
            {
                new SelectListItem{Text="Chờ duyệt", Value="Chờ duyệt"},
                new SelectListItem{Text="Đang xử lý", Value="Đang xử lý" },
                new SelectListItem{Text="Đã giao", Value="Đã giao" }}, "Lựa chọn", new { @class = "form-control", required = "required" })
                    @Html.ValidationMessageFor(model => model.TinhTrang, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-wrapper">
                <p class="col-md-10">Nhân viên xử lý</p>
                <div class="col-md-10">
                    @Html.DropDownList("MaNV", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MaNV, "", new { @class = "text-danger" })
                </div>
            </div>



            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input style="margin-left:-15px;background-color:Green" type="submit" value="Lưu" class=" button1" />
                    <a style="margin-left: -15px;" class="button1" href="~/DonHangs/Details?id=@Model.MaDH">Trở về</a>
                </div>
            </div>
        }

    </div>

</div>